sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FUNWWG90hxzGQHB5TLB/D6Ndb0NMeGzWUhs3edvaTiiQuAQoXp0jiMxxRYG1Dt9xoQiCm8p/++KVZkgUuQ6+SLwAs1lXzS8vPto0Gt9lDcNBYaKyTJQ1vyVgNAYMlDQjq585n5jR0D86PeXUIa3zr47EpvhI/XMZHgnV1Bim7qHgzciPgcnjP1BZxYDAdx5+w6mDlPXZPZjGy8ZzOAAZnmLddiwjPIB7kvDL6+iNV7SftA45z69BULHbhNdQ34VjskSk+p8C2cNEQdOVw1qxM6Ia1IKCbP96NpdxkfSBcTQtc7gx71qmMjNmEtlUqVKMIpHaqRiXHQc4gyDEBrIW9A/KgDmpriFD2szDnSJsLpi/dxAk+SlnFkRbq3S0Sn8IMBH+sbQwL07524kQtH0WpHAna31U74g9WZabW8EnOhigWzRdWCs/Ci/Pq6hFAxUAkLw0vJk+cmNlOO7XJQW2/Dq68eBnel5tom+Jqj8qWZi7SzeaQnI5OrgHKtJSgQSClrwBqKQxm9RR5U2k8IDmVW/IFQhK+F3IkgeOlO66uE2W78HEQHskbJVRdTNruaqJcQopLs/idWta3MFx2xDFxH86Pnf1ujQyjbcZBrPUs9e5HMN9dcsNcCARMaEvSZNxbRqG1FM/RGo7EPJqlLEXDimfBOH1+jJmcjiJv4RL9xA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Madman--His-Parables-and-Poems_5616
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy